const express = require('express');
const app = express();
const port = 3001;

var fs = require('fs');
var multer  = require('multer');
var upload = multer({ dest: 'uploads/' }); //setting the default folder for multer

app.post('/upload',upload.single('fileData'), (req, res,next) => {
	//below code will read the data from the upload folder. Multer     will automatically upload the file in that folder with an  autogenerated name
	fs.readFile(req.file.path,(err, contents)=> {
		if (err) {
			console.log('Error: ', err);
		}else{
			console.log('File contents ',contents);
		}
	});
});


app.listen(port, () => console.log(`Listening on port ${port}!`))
